language: node_js
node_js:
- '11'
deploy:
  provider: heroku
  api_key:
    secure: OLs58jzoHyGM4EGsoiXNTcN34xH6oUJ61Q8UlFLiVp6TR1p/E4roYUV+bUsICjmCrPBpMnG3AqHKYcO97W6O/Jok8/cXx8QpDRGNNswHjbSyopYiiZawZPR4DXLeLv0+ao34l82vQn307KFOiclcKUtTJIMa3E/UlGE5Mmr2FuKC/YubhqG/8QdUM9B+MQXDSFrCYGLEePDCGDyEwkzuvQCvQ1mi2BuWGrCOrFaYVE3ZPYa9g2pQdGo8aRfSwDBp0djS8hKYk6iyAeROxMa2XrtbBlHAF+2NGwlAUVU1My0RGv5/lngJb61ecm3IIKY68x6eF2Nxc5y3vPyN3XWz5wjeGoRFIlIRmleXFyV3A/849oBGz+/2UM59zxLXxUn1b64zp9MKXptJudv3xYPzmDcnkMy4sPv5gbqPDcH7ZzGlydY8ujDZeHG9JkPqO4Xj2lHOmnmysBTpBVSjkwYhgl2qQCCi5bDJlu7LNMOZQSe0Ls4nlvKv6O2KqhyREpkLQWTBi/tZ/jTvbkGu6+nr/3gKCTJ/jdn6KFiMACQBXty5hjNQIp60ANfv6gt/LOxD/OKof3pFpGhajXvX96tcODDZUqZtWfgmakMokR14KE45wGbhe3Rw/cprSTbWsO2vylZtOnw+A6iYL/cHt9kYLajHRUjFim+sdpsGQEicLgg=
jobs:
  include:
  - stage: test
    script:
    - npm test
  - stage: build
    script:
    - npm run start
