language: node_js
node_js:
- '11'
deploy:
  provider: heroku
  api_key:
    secure: 20b5c7e2-06b2-4ffb-ab5d-51837749bdc9
jobs:
  include:
  - stage: test
    script:
    - npm test
  - stage: build
    script:
    - npm run start
