language: node_js
node_js:
- '11'
deploy:
  provider: heroku
  api_key:
    secure: EWndtV2tBVPP2UzFzH4aWuIJycJxZlL8D7Kv7xjCxtuVhtDBfr0j1aguwan96TZ3LYpavqvrDR5GcN65k6FVTHjAd+HZss2RStGF+W9BLW7eIZyvmHtWbVd/rhoIhgZa2RPe4WPXCVx0VdaT4cfEC7P3lpYQgO7qG3D+QoLQ+BJns/JPctSYgT+M5Pzts3XL+X/gXkXjHJjN+oVRVz20y5cDfCp5NgQL3nvTiGLL2BioeQaJD5SpieuFG0eGzB7tIkkOqZnnyLaHTK7rXXIQrRCvDrmb3YU9ZDngmJ2nAHCdt24Ce1/U8GfKWeB2ElN3VfA3NHTnsJATR1r6Cbqud0zs4SlE4R0Bjb9YZRSHp9tIRCu3pp4lf2bfFfXNk99NAmHDvARPopIWE2NcDUI04Dejm03G0T0aA3AN9ThQSh4c2Io28ijTm/KZtq6FhBz8ChbkkVeJQqB0xUPiYg2nWz1aMbFqcfH2KZZzgcrEMIciCuBzHhgPOCDbCDmOh586UBu3hf7x4gmnrCqtEGtsSNgLkLQAJK84QyR1gB5YEYslPVEbVTIr1fWCfSzmdj7UiaVjs29na0DPBFT2ts6GEsIfRbR1Y5UwB5HpyGKINk/mczMAyV6kqXULjjUa4pSvgyHxAYAytr4npAM2duf1RM56mf60Yhy4E0sGrIC4Hc0=
jobs:
  include:
  - stage: test
    script:
    - npm test
  - stage: build
    script:
    - npm run start
