language: node_js
node_js:
- '11'
deploy:
  provider: heroku
  api_key:
    secure: YN0epoG8e1dPMetGcOu4FAqtIjo4ABcArg8XhrNUaV6x5mcu2zssH0c6Roerd8P0FVA8dCaYe2i2c7iCkHxbESKZNYH9UTNHqsrdhWtAtrTg2hrg9NZAqXVDCG3KTrn0TgHqFw/JC5EL+ObAM16y2QnvH1lc+1cNEtFN9wXfTJQ8tzfNAvYfK8JMkcZgrmVAGqrfJaYUQCOrWWYqWzhui/FB2ZIdryFGE4vOQJ9rZWUHpkeyVXG2M1Xo/486cGobG3Cj/WGBcLMR7XdBwUrpCDDqvLjpihNltHCTaD5YoMnu4ueReU9NwPjA5bGgdZE8G4yP+kHSZFwxiovTocVaLrWHnI4lyDenGRk/V6MR0+rWGb2aLSnoPPDsAx3Bet99j/g/Fnnv5pj6yYvNwednLqZ4YbqO72uBDX1H9XB8XACLCxKxJUDBGD7jlpHgPNCSkz4tY42Ylz++9EJ/r3nYmYI+elyKKk2o01fb15UW9uklbAqyfMZxNeAFa2ilEeznH4pAFFaKys0pMrzhPe1fuiNtmvm+R+4inmzH8hKRJo2JQjSna01jeBxom3mfBvnM4VAVCH6oqucWU2akQsLcB2mcekLczE5/u8bPrdZ/1VcwlzR0KrZpRmbxE3Mnr7jNMEMoKiPmU1ji4rLTPU2SlJ8Ow9Pq1ljdcvbk9En18Z0=
jobs:
  include:
  - stage: test
    script:
    - npm test
  - stage: build
    script:
    - npm run start
