language: node_js
node_js:
- '11'
deploy:
  provider: heroku
  api_key:
    secure: UEfaCYSrl+EABxDWi0aejojQgpigi9WSxG236+1B9jm1SCenFEvmoDAJI+rZBrI+yMB6e0WZTuM/gLWMg/7Ies+s1Jz3pX6CflUFxf64Zh5BbgjYrhR3/4WNiskIBZ3uJUxiSHA15GR9fvD7pTky537p8CBQfARaomiJwE2dydTrP5vSwx+Q1ny0BIRwZbf9vNl7/tntFFIbV6ueDhhSQOgoTio+fvZ+CxrebG7jAEWYrazOj65HSWGSSUPxKPVJH21ZmNU0ASnEXy1SKN0Oqi9XcDSSh0l91Q88R9kYzDZkgB87+N5PR0xCEY6VWMpapbp6rAchuTcwq8uWJ/4LPyM9sem9fEjqWJGeaQ6B/B3Axdh5DRQhJ6hAuSeWtgeZE04yTDL1huIr70+J8XNS0ave+vDb9pzvnmdpJhbFUL2gF9DePETgRPLKdfeKl0O0wUccWZ3jNFXhHgYqrGM9mYiFEbRj3hQajl2ORUhHW7P7kR5jgCiRVM2Wj+9o/z1JhLRl5Za5GA3jUfKXqTHDAukpxHKN2BCdd2eLGfA5aD4M6FoY/knK8gcFf0/eUhkgIheg0VrCdxCd7oWokf+ABKAqJ+/7Rn6MHYhVBt++EeWdJOfzdooG5kRGMg2Ey7phwDojG1X3ymKZLBnkLtzzceL68ISap7j5lmY9r+GnGP0=
jobs:
  include:
  - stage: test
    script:
    - npm test
  - stage: build
    script:
    - npm run start
