language: node_js
node_js:
  - "11"

jobs:
  include:
    - stage: test
      script: 
      - npm test
    - stage: build
      script:
      - npm run start
    - stage: deploy
      script:
- npm run deploy